#
# Copyright Altoros. All Rights Reserved.
#

version: '2'

volumes:
  peer0.c.example.com:
  peer1.c.example.com:

services:

  ca.c.example.com:
    container_name: ca.c.example.com
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-c
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.c.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6ab89df0193a9feeddf11ae1dba8719c2d254b397d7fded3ec2f28f01a03cbac_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.c.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6ab89df0193a9feeddf11ae1dba8719c2d254b397d7fded3ec2f28f01a03cbac_sk
    ports:
      - 9054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../artifacts/crypto-config/peerOrganizations/c.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../artifacts/fabric-ca-server-config-c.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml

  peer0.c.example.com:
    container_name: peer0.c.example.com
    extends:
      file: base-intercept.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.c.example.com
      - CORE_PEER_LOCALMSPID=cMSP
      - CORE_PEER_ADDRESS=peer0.c.example.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.c.example.com:5984
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/c.example.com/peers/peer0.c.example.com/:/etc/hyperledger/crypto/peer
        - peer0.c.example.com:/var/hyperledger/production
    depends_on:
      - ca.c.example.com
      - couchdb.c.example.com
    

  peer1.c.example.com:
    container_name: peer1.c.example.com
    extends:
      file: base-intercept.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.c.example.com
      - CORE_PEER_LOCALMSPID=cMSP
      - CORE_PEER_ADDRESS=peer1.c.example.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.c.example.com:5984
    ports:
      - 9056:7051
      - 9058:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/c.example.com/peers/peer1.c.example.com/:/etc/hyperledger/crypto/peer
        - peer1.c.example.com:/var/hyperledger/production
    depends_on:
      - ca.c.example.com
      - couchdb.c.example.com
    

  # fabric-rest api server
  api.c.example.com:
    extends:
      file: base-intercept.yaml
      service: api-base
    container_name: api.c.example.com
    ports:
      - 4002:4000
    environment:
      - ORG=c
      - PORT=4000
    volumes:
      - ../artifacts/hosts/c/api_hosts:/etc/hosts
    depends_on:
      - peer0.c.example.com
      - peer1.c.example.com
    

  cli.example.com:
    container_name: cli.example.com
    extends:
      file: base-intercept.yaml
      service: cli-base
    volumes:
      - ../artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/etc/hyperledger/crypto/orderer/tls

  cli.c.example.com:
    container_name: cli.c.example.com
    extends:
      service: cli.example.com
    environment:
      - CORE_PEER_LOCALMSPID=cMSP
    volumes:
    #    - ../artifacts/hosts/c/cli_hosts:/etc/hosts
        - ../artifacts/crypto-config/peerOrganizations/c.example.com/users/Admin@c.example.com:/etc/hyperledger/crypto/peer
    

  cliNoCryptoVolume.c.example.com:
    container_name: cliNoCryptoVolume.c.example.com
    extends:
      file: base-intercept.yaml
      service: cli-base
    environment:
      - CORE_PEER_LOCALMSPID=cMSP
    volumes:
        - ../artifacts/hosts/c/cli_hosts:/etc/hosts

  # simple http server to disseminate certificates
  www.c.example.com:
    extends:
      file: base-intercept.yaml
      service: www-base
    container_name: www.c.example.com
    ports:
      - 8083:80

  couchdb.c.example.com:
    container_name: couchdb.c.example.com
    image: hyperledger/fabric-couchdb:0.4.10
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
#    environment:
#      - COUCHDB_USER=
#      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 7984:5984
